sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t arunachavj/docker-react   -f Dockerfile.dev .

script:
  - docker run -e CI=true arunachavj/docker-react npm run test

